import "./globals.css";

export const metadata = {
  title: "App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body className='bg-[#141414] text-white scrollbar-none'>{children}</body>
    </html>
  );
}
